

# This file was *autogenerated* from the file generate_curves.sage
from sage.all_cmdline import *   # import sage library

_sage_const_12007 = Integer(12007); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_100 = Integer(100); _sage_const_0p0 = RealNumber('0.0')
import pandas as pd

# 1. Paramètres (p=12007 -> environ 1000 courbes supersingulières possibles)
p = _sage_const_12007  
F2 = GF(p**_sage_const_2 , modulus=x**_sage_const_2 +_sage_const_1 , names=('i',)); (i,) = F2._first_ngens(1)

nodes_data = []
curves_found = {} 
queue = []

# 2. Recherche de la courbe "graine" (Seed)
print("Recherche de la courbe de départ...")
for a in range(_sage_const_1 , p):
    E = EllipticCurve(F2, [a, _sage_const_0 ])
    if E.is_supersingular():
        j = E.j_invariant()
        curves_found[j] = E
        queue.append(E)
        break

# 3. Exploration exhaustive du graphe (BFS)
print("Début de l'exploration du graphe...")
while queue:
    E_curr = queue.pop(_sage_const_0 )
    
    try:
        # On utilise les isogénies de degré 2 (standard SIDH/SIKE)
        isogenies = E_curr.isogenies_prime_degree(_sage_const_2 )
        
        for phi in isogenies:
            E_next = phi.codomain()
            j_next = E_next.j_invariant()
            
            if j_next not in curves_found:
                # Vérification mathématique de supersingularité
                if E_next.is_supersingular():
                    curves_found[j_next] = E_next
                    queue.append(E_next)
                    
                    if len(curves_found) % _sage_const_100  == _sage_const_0 :
                        print(f"Courbes trouvées : {len(curves_found)}")
    except:
        continue

# 4. Extraction des caractéristiques pour l'IA (Normalisation)
for idx, (j, E) in enumerate(curves_found.items()):
    coeffs = j.list()
    # j_real et j_imag normalisés entre 0 et 1 pour le modèle de Rayhana
    jr = float(coeffs[_sage_const_0 ]) / p
    ji = float(coeffs[_sage_const_1 ]) / p if len(coeffs) > _sage_const_1  else _sage_const_0p0 
    
    nodes_data.append({
        "node_id": idx,
        "j_real": jr,
        "j_imag": ji
    })

# 5. Sauvegarde dans le dossier datasets
df = pd.DataFrame(nodes_data)
df.to_csv("../datasets/node_features.csv", index=False)

print(f"\n✅ Succès ! {len(nodes_data)} courbes extraites.")
print(f"Fichier sauvegardé : datasets/node_features.csv")

