

# This file was *autogenerated* from the file generate_curves.sage
from sage.all_cmdline import *   # import sage library

_sage_const_12007 = Integer(12007); _sage_const_2 = Integer(2); _sage_const_1 = Integer(1); _sage_const_0 = Integer(0); _sage_const_1000 = Integer(1000); _sage_const_100 = Integer(100); _sage_const_0p0 = RealNumber('0.0')
import pandas as pd

# 1. Paramètres
p = _sage_const_12007  # Nombre premier (p = 3 mod 4 pour faciliter la supersingularité)
F2 = GF(p**_sage_const_2 , modulus=x**_sage_const_2 +_sage_const_1 , names=('i',)); (i,) = F2._first_ngens(1)

# Liste pour stocker nos résultats
nodes_data = []
curves_found = {} # Pour éviter les doublons via j-invariant
queue = []

# 2. Trouver la TOUTE PREMIÈRE courbe (La graine)
# On cherche une courbe supersingulière de départ par balayage
print("Recherche de la courbe de départ...")
for a in range(_sage_const_1 , p):
    E = EllipticCurve(F2, [a, _sage_const_0 ])
    if E.is_supersingular():
        j = E.j_invariant()
        curves_found[j] = E
        queue.append(E)
        break

# 3. Exploration avec vérification mathématique à chaque pas

while len(curves_found) < _sage_const_1000  and queue:
    E_curr = queue.pop(_sage_const_0 )
    
    # On calcule les voisines (isogénies de degré 2)
    try:
        isogenies = E_curr.isogenies_prime_degree(_sage_const_2 )
        
        for phi in isogenies:
            E_next = phi.codomain()
            j_next = E_next.j_invariant()
            
            # CONDITION DOUBLE : Nouveau j-invariant ET certification mathématique
            if j_next not in curves_found:
                if E_next.is_supersingular(): # <--- LA VÉRIFICATION QUE TU VOULAIS
                    curves_found[j_next] = E_next
                    queue.append(E_next)
                    
                    if len(curves_found) % _sage_const_100  == _sage_const_0 :
                        print(f"nombre de courbes touvées : {len(curves_found)}/1000")
            
            if len(curves_found) >= _sage_const_1000 :
                break
    except:
        continue

# 4. Transformation en Dataset pour l'IA
for idx, (j, E) in enumerate(curves_found.items()):
    coeffs = j.list()
    # On normalise pour ton partenaire (valeurs entre 0 et 1)
    jr = float(coeffs[_sage_const_0 ]) / p
    ji = float(coeffs[_sage_const_1 ]) / p if len(coeffs) > _sage_const_1  else _sage_const_0p0 
    
    nodes_data.append({
        "node_id": idx,
        "j_real": jr,
        "j_imag": ji
    })

# 5. Sauvegarde
df = pd.DataFrame(nodes_data)
df.to_csv("../datasets/node_features.csv", index=False)
print(f"Succès ! Dataset créé avec {len(nodes_data)} courbes supersingulières.")

